# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29cb5ab63b3e980a7bd688aa7c508e2e242a940dd680d079a18144386f60c61669c378abd21c3e88970a68cf8fae93f5ce8f8a681b7e46c118e22361aca0db64

test:
  secret_key_base: d62731ab4db5b3c5c75c8aa82a270ee49fc2034701e1bc8a2ddaeb5a511115574480daa0a78a27bf9b6552cfc06dc9d4d715236ecd4e6a2c1b4cf237e50f0606

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
